name = "colg"
main = ".open-next/worker.js"
compatibility_date = "2026-02-04"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
SCAN_DISABLE = "1"
OPENAI_API_KEY = ""
BOT_API_KEYS = ""
NEXT_PUBLIC_CF_BEACON_TOKEN = ""
NEXT_PUBLIC_SITE_URL = ""

[[d1_databases]]
binding = "DB"
database_name = "colg"
database_id = "05726e5c-7811-4fb4-b59e-2e05ae1afe12"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "77fc229393c54e34a391e913ea053781"
preview_id = "49adb08231e443a6bf30828096d3bfae"
